import type { Metadata } from "next";
import Header from "@/components/header";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const lang = 'ar';
  return (
    <html lang={lang} dir={lang === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={` antialiased`}
      >
         <Header />
        {children}
      </body>
    </html>
  );
}
